DROP VIEW Positionsupervises;
drop view playernationalities;
drop view SalaryData;
DROP VIEW Ticketspergame;
DROP VIEW TEAMWITHINFO;
DROP VIEW EmployeeWithInfo;
DROP VIEW PlayerWithInfo;
DROP VIEW CoachWithInfo;
DROP TABLE ticket_category cascade constraints;
DROP TABLE tickets cascade constraints;
DROP SEQUENCE TICKETS_SEQ;
DROP TABLE game cascade constraints;
DROP TABLE game_location CASCADE CONSTRAINTS;
DROP TABLE playsfor cascade constraints;
DROP TABLE player cascade constraints;
DROP TABLE coach_position cascade constraints;
DROP TABLE cposition CASCADE CONSTRAINTS;
DROP TABLE coach cascade constraints;
DROP TABLE team cascade constraints;
DROP TABLE flat cascade constraints;
DROP TABLE dressingroom cascade constraints;
DROP TABLE stadium cascade constraints;
DROP TABLE employee_position cascade constraints;
DROP TABLE eposition cascade constraints;
DROP TABLE employees cascade constraints;
DROP TABLE office cascade constraints;
DROP TABLE club cascade constraints;
DROP TABLE fan cascade constraints;